name: Auto-Release

on:
  workflow_run:
    workflows: ["\"\"\"Java\"\"\" CI"]
    types: [completed]

jobs:
  createRelease:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - uses: fwilhe2/setup-kotlin@main

      - name: Switch branch
        run: git switch ${{ github.event.workflow_run.head_branch }}

      - name: Download jar
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: gradle.yml
          name: community-mod
          path: "."

      - name: Get latest commit
        id: getCommit
        uses: actions/checkout@v2
        with:
          ref: master
          path: ${{ github.event.repository.name }}

      - name: Run kotlin code
        run: kotlinc -script workflows/main.kts ${{ github.event.workflow_run.head_sha }}

      - name: Get description string
        uses: pCYSl5EDgo/cat@master
        id: getDescription
        with:
          path: ./output.json

      - name: Get tag string
        uses: pCYSl5EDgo/cat@master
        id: getTag
        with:
          path: ./tag.json

      - name: Debug printing
        run: |
          ls
          echo -----
          cat output.json
          echo -----
          cat tag.json

      - name: Create release
        id: createRelease
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ${{ github.event.repository.name }}.jar
          artifactContentType: application/zip

          tag: ${{ steps.getTag.outputs.text }}
          name: "Lorem ipsum dolor"
          body: ${{ steps.getDescription.outputs.text }}
          prerelease: false
